### ISSUE TITLE
Figure out how to handle rollbacks

### ISSUE THREAD

**Issue by SaintWish** [MSRevive/nexus2#2]
One method of handling rollbacks is spinning up another database table that store snap shots of the character data like every hour or something?

**Comment by fegged** [comment]
Depends on how much storage it takes, old FN took one every 4 hours

**Comment by SaintWish** [comment]
> Depends on how much storage it takes, old FN took one every 4 hours

Storage shouldn't be to much of an issue because we're using SQLite, but yeah having the system do a backup of every character every hour might be a bit much for it to handle.

**Comment by pbarnum** [comment]
I'm curious, what was the reasoning behind choosing SQLite over something like MySQL/Postgres or a noSQL solution?

**Comment by SaintWish** [comment]
There really wasn't a need for a database server like MySQL because we figured it would be kind of overkill for what we needed it for. I guess we could have used a noSQL solution, but it didn't really cross our minds and I have never worked with a noSQL database before.

**Comment by pbarnum** [comment]
Totally understandable and you've built a working solution thus far so no point in changing it, at least for now.

**Comment by SaintWish** [comment]
Indeed, and if we have to in the future it wouldn't be that difficult to switch the system since we're using a entity framework instead of raw SQLite. 

Though because we are using a database now, it's kind of difficult to think of the best way to handle rollbacks because I would want to make it mostly automatic for the staff.

**Comment by pbarnum** [comment]
What about separating the player data from the character data? New character table would include a foreign key to the player table, and a unique composite index between the player id and the version number (one too many). You can also impose a maximum version history if desired. A background worker could then perform backups every 5 minutes or so, and calculate a checksum on the data to prevent unnecessary backups. This could also be simplified to backup only when the data is updated.

**Comment by pbarnum** [comment]
> Indeed, and if we have to in the future it wouldn't be that difficult to switch the system since we're using a entity framework instead of raw SQLite.

I'm personally a fan of running raw SQL. ORMs tend to add a lot of overhead when running simple commands and some often make commands more complicated than they need to be. Additionally, they lock the project into a very opinionated methodology, which makes refactoring, or replacement much more complicated.

**Comment by SaintWish** [comment]
> What about separating the player data from the character data? New character table would include a foreign key to the player table, and a unique composite index between the player id and the version number (one too many). You can also impose a maximum version history if desired. A background worker could then perform backups every 5 minutes or so, and calculate a checksum on the data to prevent unnecessary backups. This could also be simplified to backup only when the data is updated.

That's a pretty good idea, is that something you'd be willing to help with?

**Comment by pbarnum** [comment]
Yeah I can get that done 👍

**Comment by SaintWish** [comment]
Cheers, we can talk about the details in Discord.

**Comment by SaintWish** [comment]
Done thanks to @pbarnum will be released for v1.1.0
